export const RichestMans = [
  {
    rank: "1",
    name: "Elon Musk",
    netWorth: "$244.2 B",
    sourceOfWealth: "Tesla, SpaceX",
    country: "United States",
  },
  {
    rank: "2",
    name: "Bernard Arnault & family",
    netWorth: "$208.8 B",
    sourceOfWealth: "LVMH",
    country: "France",
  },
  {
    rank: "3",
    name: "Jeff Bezos",
    netWorth: "$155.9 B",
    sourceOfWealth: "Amazon",
    country: "United States",
  },
  {
    rank: "4",
    name: "Larry Ellison",
    netWorth: "$144.9 B",
    sourceOfWealth: "Oracle",
    country: "United States",
  },
  {
    rank: "5",
    name: "Warren Buffet",
    netWorth: "$118.9 B",
    sourceOfWealth: "Berkshire Hathaway",
    country: "United States",
  },
  {
    rank: "6",
    name: " Bill Gates",
    netWorth: "$113.0 B",
    sourceOfWealth: "Microsoft",
    country: "United States",
  },
  {
    rank: "7",
    name: "Larry Page",
    netWorth: "	$109.9 B",
    sourceOfWealth: "Google",
    country: "United States",
  },
  {
    rank: "8",
    name: "Sergey Brin",
    netWorth: "$104.4 B",
    sourceOfWealth: "Google",
    country: "United States",
  },
  {
    rank: "9",
    name: "Mark Zuckerberg",
    netWorth: "$101.3 B",
    sourceOfWealth: "Facebook",
    country: "United States",
  },
  {
    rank: "10",
    name: "Steve Ballmer",
    netWorth: "$99.6 B",
    sourceOfWealth: "Microsoft",
    country: "United States",
  },
];
